name: Update posts

on:
  schedule:
  - cron: "0 2 * * 1"
  
jobs:
  update:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: pnpm ci
      - run: pnpm run scrape
